In [6]:
import numpy as np

In [10]:
#columns = [age, heart_rate, cholesterol, blood_pressure]
patients_data = np.array([
[45, 80, 200, 120],
[60, 90, 240, 140],
[30, 70, 180, 110],
[50, 85, 220, 130],
[65, 95, 260, 150]])

In [13]:
patients_data.shape

(5, 4)

In [15]:
pation=patients_data.shape[0]
pation

5

In [16]:
pation=patients_data.shape[1]
pation

4

In [17]:
patients_data[0]

array([ 45,  80, 200, 120])

In [18]:
patients_data[:,0]       #note# all row and colum0

array([45, 60, 30, 50, 65])

In [19]:
patients_data[:,3]   

array([120, 140, 110, 130, 150])

In [21]:
age=patients_data[:,0]       
age.mean()

np.float64(50.0)

In [32]:
heart=patients_data[:,1]
heart.max()




np.int64(95)

In [33]:
cholesterol=patients_data[:,2]
cholesterol.min()

np.int64(180)

In [36]:
np.where(patients_data[:,3]>130)

(array([1, 4]),)

In [40]:
cholesterol=patients_data[:, 2] >= 240
cholesterol

array([False,  True, False, False,  True])

In [52]:
np. where(patients_data[:, 2] >= 240)


(array([1, 4]),)

In [50]:
np.where(patients_data[:, 0] > 50)

(array([1, 4]),)

In [59]:
highBp = patients_data[:, 3] > 140
highch = patients_data[:, 2] > 240
print(highBp,highch)

[False False False False  True] [False False False False  True]


In [55]:
patients_data[(patients_data[:, 3] > 140) | (patients_data[:, 2] > 240)]# another way 

array([[ 65,  95, 260, 150]])

In [67]:
ages = patients_data[:, 0]
under_50 = patients_data[ages < 50]
above_50 = patients_data[ages >= 50]
avg_under_50 = under_50[:, 1].mean()
avg_above_50 = above_50[:, 1].mean()

avg_under_50, avg_above_50###Older patients  have a higher average heart rate

(np.float64(75.0), np.float64(90.0))

In [61]:
under_50.mean()

np.float64(104.375)

In [68]:
patients_data[patients_data[:, 3].argmax()]

array([ 65,  95, 260, 150])

In [69]:
patients_data[patients_data[:, 1].argmin()]

array([ 30,  70, 180, 110])

In [70]:
ages = patients_data[:, 0]
bp = patients_data[:, 3]

In [71]:
bp_under_50 = bp[ages < 50].mean()
bp_50_above = bp[ages >= 50].mean()
bp_under_50, bp_50_above


(np.float64(115.0), np.float64(140.0))