In [4]:
import numpy as np

In [5]:
arr=np.array([[12,23,23,10],[12,20,34,12]])

In [6]:
arr

array([[12, 23, 23, 10],
       [12, 20, 34, 12]])

In [7]:
arr.shape

(2, 4)

In [8]:
rows=arr.shape[0]
rows

2

In [9]:
colo=arr.shape[1]

In [10]:
colo

4

In [12]:
arr.dtype

dtype('int64')

In [13]:
zeroarray=np.zeros(7,"int")
zeroarray


array([0, 0, 0, 0, 0, 0, 0])

In [14]:
onearay=np.ones([5,5],int)
onearay

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [15]:
myrange=np.arange(0,50,2)
myrange

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [16]:
array1=np.array([3,4,1,6])
array2=np.array([10,7,1,5])
array1*array2

array([30, 28,  1, 30])

In [17]:
array1*2


array([ 6,  8,  2, 12])

In [18]:
array1-2

array([ 1,  2, -1,  4])

In [19]:
array1**3

array([ 27,  64,   1, 216])

In [20]:
array1.T

array([3, 4, 1, 6])

In [2]:
import numpy as np

In [3]:
A=np.array([[1,2,3],[4,5,6]])
print(A)
print('\n')
B=np.array([[7,8],[9,10],[11,12]])
print(B)
print('\n')
np.dot(A,B)

[[1 2 3]
 [4 5 6]]


[[ 7  8]
 [ 9 10]
 [11 12]]




array([[ 58,  64],
       [139, 154]])

In [4]:
arr=np.array([[12,23,23,10],[12,20,34,12]])

In [5]:
lastelement=arr[arr.shape[0]-1]
lastelement


array([12, 20, 34, 12])

In [6]:
A=np.array([[1,2,3],[4,5,6]])
A[ :2, 2:]

array([[3],
       [6]])

In [7]:
A[1:2,1:]

array([[5, 6]])

In [8]:
A[ :2, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
A[1:,:]

array([[4, 5, 6]])

In [11]:
arr=np.array([10,7,1,5])

In [13]:
arr=np.array([10,7,1,5,5,6,7,2,12,23])

In [16]:
a=np.array([10,21,30])
a

array([10, 21, 30])

In [18]:
a[0:5]=100
a

array([100, 100, 100])

In [21]:
a[1]

np.int64(100)

In [22]:
arr=np.array([[12,23,23,10],[12,20,34,12]])
arr[:3,: :2]

array([[12, 23],
       [12, 34]])

In [23]:
newArr=np.arange(1,13)
newArr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [24]:
reshapeArr=newArr.reshape((3,4))
reshapeArr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
reshapeArr=newArr.reshape(4,3)
reshapeArr


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [28]:
x=np.array([1,2,3])
y=np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [32]:
arr2dA=([1,2,3])
arr2dB=([3,2,1])
result=np.concatenate([arr2dA,arr2dB],axis=0)
result

array([1, 2, 3, 3, 2, 1])

In [43]:
grid=np.arange(16).reshape((4,4))
print(grid)
print("\n")
upper,lower=np.vsplit(grid,[1])#mean row split from 0 to 1 and the rest is in the lower
print(upper)
print("\n")
print(lower)



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[[0 1 2 3]]


[[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [46]:
grid=np.arange(1,17).reshape((4,4))
a,b=np.hsplit(grid,[3])
print(a)
print("--------")
print(b)

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
--------
[[ 4]
 [ 8]
 [12]
 [16]]


In [49]:
grid=np.arange(20).reshape((4,5))
a,b=np.hsplit(grid,[2])
print(a)
print("--------")
print(b)

[[ 0  1]
 [ 5  6]
 [10 11]
 [15 16]]
--------
[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [55]:
grid=np.arange(20).reshape((4,5))
a,b,z=np.hsplit(grid,[2,4])# h mean coloum split from 0 to 1 then 2to 3 and the rest in z
print(a)
print("--------")
print(b)
print("--------")
print(z)

[[ 0  1]
 [ 5  6]
 [10 11]
 [15 16]]
--------
[[ 2  3]
 [ 7  8]
 [12 13]
 [17 18]]
--------
[[ 4]
 [ 9]
 [14]
 [19]]


In [52]:
arr=np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [54]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [57]:
a=np.random .randn(10)
a

array([ 0.72280709,  0.24952727, -0.90984303,  0.43439128, -1.97805842,
       -0.2942123 ,  0.36760012, -1.17483006, -2.30316242,  0.84328632])

In [58]:
a=np.random .randint(5,100,20)
b=np.random .randint(5,100,20)
print(a)
print(b)


[44 42 78 36 20 32 34 95 15 85 51 20 42 95 37 91 87 47 18 55]
[16 94 89 60 77 20 22 62 13 61 67 71 53  8 60 55 30 12  5 36]


In [59]:
np.add(a,b)

array([ 60, 136, 167,  96,  97,  52,  56, 157,  28, 146, 118,  91,  95,
       103,  97, 146, 117,  59,  23,  91], dtype=int32)

In [60]:
np.maximum(a,b)

array([44, 94, 89, 60, 77, 32, 34, 95, 15, 85, 67, 71, 53, 95, 60, 91, 87,
       47, 18, 55], dtype=int32)

In [61]:
np.minimum(a,b)

array([16, 42, 78, 36, 20, 20, 22, 62, 13, 61, 51, 20, 42,  8, 37, 55, 30,
       12,  5, 36], dtype=int32)

In [68]:
a=np.array([1,2,3,4])
b=np.array([100,200,300,400])
condition=np.array([True,True,False,False])
answer2=np.where(condition,a,b)
answer2

array([  1,   2, 300, 400])

In [73]:
arr=np.random.randn(5,5)
arr

array([[-2.27722421,  0.47044278, -0.16533831,  1.4215396 ,  0.52499036],
       [-0.58503613, -0.4437919 , -0.96057892,  0.14604079, -1.4405355 ],
       [-0.71714331, -0.80677547,  1.12661333, -0.49905276,  1.58112458],
       [ 0.25295776, -0.04035718,  2.01825052, -0.41581057,  0.51557898],
       [-0.87454421,  0.22506606, -0.93646023, -0.27482558,  1.88929827]])

In [74]:
np.where(arr<0,0,arr)

array([[0.        , 0.47044278, 0.        , 1.4215396 , 0.52499036],
       [0.        , 0.        , 0.        , 0.14604079, 0.        ],
       [0.        , 0.        , 1.12661333, 0.        , 1.58112458],
       [0.25295776, 0.        , 2.01825052, 0.        , 0.51557898],
       [0.        , 0.22506606, 0.        , 0.        , 1.88929827]])

In [76]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [77]:
arr.sum()

np.int64(45)

In [78]:
print(arr.sum(1))#row

[ 6 15 24]


In [79]:
print(arr.sum(0))#coloum

[12 15 18]


In [80]:
arr.mean()

np.float64(5.0)

In [81]:
arr.std()

np.float64(2.581988897471611)

In [82]:
arr.var()

np.float64(6.666666666666667)

In [87]:
boolean=np.array ([False,True,True])
boolean.any()

np.True_

In [89]:
a=np.array([-2,5,4,-8,0])
print(a)

[-2  5  4 -8  0]


In [91]:
print(np.sort(a))# يرتب الارقام من الاصغر لاكبر

[-8 -2  0  4  5]


In [92]:
print(-np.sort(a))#العكس

[ 8  2  0 -4 -5]


In [93]:
countries=np.array(['france','oman','saudi','russia','germany','russia','USA'])
np.unique(countries)

array(['USA', 'france', 'germany', 'oman', 'russia', 'saudi'], dtype='<U7')