In [1]:
import numpy as np

In [2]:
pationId=np.array([101,102,103,104,105])
heartRate=np.array([72,110,95,130,88])
statue=np.where(heartRate>100 ,"critical","stable")# patiom
print("pation ID: ",pationId)
print("heart rates: ",heartRate)
print("statues: ",statue)

pation ID:  [101 102 103 104 105]
heart rates:  [ 72 110  95 130  88]
statues:  ['stable' 'critical' 'stable' 'critical' 'stable']


In [6]:
#temppp filling non=0
tempreture=np.array([37.2,36.5,0,38.1,0,36.8])
condition=tempreture!=0
filterd=tempreture[condition]
avgTemp=filterd.mean()
print(avgTemp)
cleanedTemb=np.where(tempreture==0,avgTemp,tempreture)
print("original: ",tempreture)
print("cleaned: ",cleanedTemb )
                    


37.150000000000006
original:  [37.2 36.5  0.  38.1  0.  36.8]
cleaned:  [37.2  36.5  37.15 38.1  37.15 36.8 ]


In [9]:
condition2 = cleanedTemb > 37# number grate then 37
condition2
filterd =cleanedTemb[condition2]
filterd

array([37.2 , 37.15, 38.1 , 37.15])

In [10]:
ages=np.array([23,25,26,70,50])
bp=np.array([120,150,135,160,145])
high= np.where((ages>60)|(bp>140),"high", "normal")
print("the age: ",ages)
print(" the blood pressure: ",bp)
print(high)

the age:  [23 25 26 70 50]
 the blood pressure:  [120 150 135 160 145]
['normal' 'high' 'normal' 'high' 'high']


In [11]:
salaris=np.array([400,600,550,300,700])
condition=salaris>=500
bones=np.where(condition, salaris+100,salaris+50)
print(bones)

[450 700 650 350 800]


In [15]:
marks=np.array([90,75,60,82,90,99,95,86])
grades=np.where(marks>=85,np.where(marks>=95,"A+","A"),np.where(marks>=70,"B","C"))
print(marks)
print(grades)

[90 75 60 82 90 99 95 86]
['A' 'B' 'C' 'B' 'A' 'A+' 'A+' 'A']


In [16]:
purches=np.array([50,200,40,35,100,120])
discount=np.where(purches>100,purches*0.9,purches*0.8)
print(discount)

[ 40. 180.  32.  28.  80. 108.]


In [19]:
heartRate = np.array([80, 130, 110, 120, 70])
oxygen = np.array([95, 80, 92, 88, 70])

emergency = np.where((heartRate > 120) & (oxygen < 90), "emergency", "normal")

print("heart Rate:", heartRate)
print("oxygen level:", oxygen)
print(emergency)

heart Rate: [ 80 130 110 120  70]
oxygen level: [95 80 92 88 70]
['normal' 'emergency' 'normal' 'normal' 'normal']


In [20]:
a = np.linspace(0, 1, num=10)
print(a)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [21]:
array, c = np.linspace(0, 10, num=5, retstep=True)
print("Step Size:", c)

Step Size: 2.5


In [22]:
arr = np.array([[1, 2], [3, 4], [5, 6]])

print(arr.ndim)   # Output: 2
print(arr.shape)  # Output: (3, 2)
print(arr.size)

2
(3, 2)
6
